pipeline {
    agent any

    environment {
        TF_WORKSPACE = "default"
        TF_CLI_ARGS = "-no-color"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'develop', url: 'https://github.com/manju230/tf-project-5.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('dev/vpc') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Format') {
            steps {
                dir('dev/vpc') {
                    sh 'terraform fmt -recursive'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('dev/vpc') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('dev/vpc') {
                    sh 'terraform plan -var-file=terraform.tfvars -out=tfplan'
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    def userInput = input(
                        id: 'Proceed1', 
                        message: 'Do you want to apply this Terraform plan?',
                        parameters: [
                            choice(name: 'Confirm', choices: ['No', 'Yes'], description: 'Select Yes to apply, No to abort')
                        ]
                    )
                    if (userInput == 'No') {
                        error("Terraform apply aborted by user.")
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('dev/vpc') {
                    sh 'terraform apply tfplan'
                }
            }
        }
    }

    post {
        success {
            echo 'Terraform pipeline completed successfully!'
        }
        failure {
            echo 'Terraform pipeline failed or was aborted.'
        }
    }
}
